ucldc/rikolti

- spark-mapper/nuxeo_media_mapper.py
> Nuxeo Media Mapper

- metadata-fetcher/OACFetcher.py
- metadata-fetcher/deploy-version.sh
- metadata-fetcher/lambda_function.py
- metadata-fetcher/requirements.txt
- metadata-fetcher/tests.py
- spark-mapper/.flake8
- spark-mapper/oac_mapper.py
- spark-mapper/oac_mapper_suppress_description.py
- spark-mapper/oac_mapper_suppress_publisher.py
> OAC mapper

- metadata-mapper/validate_mapping.py
Hey @amywieliczka -- I think this is the correct fix for the import statements? 
Also, I figure using github like this is the easiest way to communicate about these kinds of things, but lmk if a different workflow seems better :)
> Fix import statements

- metadata-fetcher/OAIFetcher.py
OK I think this makes more sense...
> Simplify query parameter vars for OAI fetcher

- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/oai/cca_vault_mapper.py
- metadata_mapper/mappers/oai/chapman_oai_dc_mapper.py
- metadata_mapper/mappers/oai/islandora_mapper.py
- metadata_mapper/mappers/oai/oai_mapper.py
Draft because I need to test and squash.
> Implement chapman_oai_dc mapper

- metadata_fetcher/fetchers/oai_fetcher.py
The &set=None parameter was preventing fetch
from interviews.televisionacademy.com
> Exclude map param when not present

- metadata_fetcher/fetch_registry_collections.py
- metadata_mapper/lambda_function.py
- metadata_mapper/map_registry_collections.py
- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
- metadata_mapper/validate_mapping.py
- metadata_mapper/validate_registry_collections.py
> Adds the existing "Solr Updater" mapping to the enrichment chain

- metadata_mapper/lambda_function.py
- metadata_mapper/map_registry_collections.py
- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/oai/chapman_mapper.py
- metadata_mapper/mappers/oai/chapman_oai_dc_mapper.py
- metadata_mapper/mappers/oai/islandora_mapper.py
- metadata_mapper/mappers/oai/oai_mapper.py
- metadata_mapper/requirements.txt
Chapman and CCA vault need to be tested / compared with Solr again before this is ready for review.
> Revert the deprecation of some methods

- metadata_mapper/map_registry_collections.py
- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/oai/samvera_mapper.py
- metadata_mapper/mappers/oai/tv_academy_mapper.py
- metadata_mapper/mappers/oai/up_mapper.py
- metadata_mapper/mappers/oai/yosemite_mapper.py
Follows https://github.com/ucldc/rikolti/pull/312
> 1. Reimplement oai mappers

- metadata_mapper/mappers/mapper.py
* Add is_shown_at and is_shown_by
* Sort solr_doc by keys
> Adjust solr_doc in mapper for easier validation

- metadata_mapper/mappers/validator.py
@timfrazee I'm putting validator tweaks, improvements here.
> Validator improvements

- metadata_mapper/lambda_function.py
- metadata_mapper/map_registry_collections.py
- metadata_mapper/validate_mapping.py
@lthurston, if you've made any changes to this mapper_type lookup map, please let me know. I haven't had much time to make updates to the collection registry, so it's unlikely those changes have been propagated through, and this work here will break things.
> Use rikolti_mapper_type instead of mapper_type

- metadata_mapper/lambda_shepherd.py
- metadata_mapper/mappers/mapper.py
There are a few commits here that address enrichment and tooling issues that came up during mapping development. The extended commit comments offer context.
> Enrichment and tooling adjustments

- README.md
This PR is complimentary to these updates in aws-mwaa-local-runner: https://github.com/ucldc/aws-mwaa-local-runner/pull/4
> Chore: describe docker socket setup in readme

- metadata_mapper/mappers/flickr/sdasm_mapper.py
The SDASM mapper saw a meaningful improvement in identifier values: 
Legacy Value: `['AL-135B', '38276802']`
Rikolti Value: `['Catalog: AL-135B', 'PictionID: 38276802', 'Filename: AL-135B']`
However, this improvement causes lots of errors in the validation reports. This custom SdasmValidator removes labels (ex: `['AL-135B', '38276802', 'AL-135B']`), de-duplicates the remaining values (ex: `['AL-135B', '38276802']`), and then sorts both the legacy and the rikolti values to do an order-agnostic comparison of Legacy values and Rikolti values. 
The SDASM mapper also sees many validation errors for "Image" vs. "image". Unlike with identifier, this is not an intentional Rikolti improvement. We don't know where this comes from. But we also don't think it matters. If we uncover some issue with a …
> Feat: Approve SDASM Image/image, identifier labels

- .github/workflows/ci.yml
- .github/workflows/dags_test.yml
> [bug]: fix ruff ci

- metadata_fetcher/fetchers/Fetcher.py
- metadata_fetcher/fetchers/ucd_json_fetcher.py
- metadata_fetcher/requirements.txt
- metadata_mapper/lambda_function.py
- metadata_mapper/mappers/ucd_json/ucd_json_mapper.py
> UCD fetcher / mapper

- dags/validate_by_mapper_type.py
- metadata_fetcher/fetchers/solr_fetcher.py
- metadata_fetcher/fetchers/ucd_json_fetcher.py
- metadata_mapper/map_registry_collections.py
- metadata_mapper/mappers/constants.py
- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/ucsd_blacklight/ucsd_blacklight_mapper.py
@timfrazee This is ready for your review, too.
Example response: [https://lib-metadata.ucsd.edu/solr/blacklight/select?rows=100&cursorMark=%2A&q=collections_tesim%3Abb08204951&wt=json&sort=id+asc](https://lib-metadata.ucsd.edu/solr/blacklight/select?rows=100&cursorMark=%2A&q=collections_tesim%3Abb08204951&wt=json&sort=id+asc)
> solr fetcher / blacklight mapper

- metadata_mapper/mappers/oai/cca_vault_mapper.py
- metadata_mapper/validator/validation_mode.py
- metadata_mapper/validator/validator.py
Apply mode to identifier, creator, date, format, subject, and temporal fields
> Add list order insensitive validation mode

- README.md
- dags/utils_by_mapper_type.py
- metadata_fetcher/fetch_registry_collections.py
- Report out errored collections but continue harvesting
- Update documentation
> Feat: Non-blocking errors

- dags/utils_by_mapper_type.py
- metadata_mapper/map_registry_collections.py
- metadata_mapper/mappers/mapper.py
- metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
- utils/versions.py
Resolves non-starter errors when running harvests using offsets
Resolves mapper and validator errors when running harvests using limits
Adds a custom validator for Nuxeo is_shown_by fields
Tweaks Nuxeo type mapping to remove instances of `type=[None]` in favor of `type=None`
> Offset errors

- dags/harvest_dag.py
- dags/shared_tasks/content_harvest_tasks.py
- dags/shared_tasks/fetching_tasks.py
- dags/shared_tasks/indexing_tasks.py
- dags/shared_tasks/mapping_tasks.py
- dags/shared_tasks/shared.py
- env.example
- metadata_mapper/lambda_function.py
- metadata_mapper/lambda_shepherd.py
- metadata_mapper/map_registry_collections.py
This PR adds send_event_to_sns to report the success of all tasks in the harvest_collection DAG. 
It also adds an on_failure_callback to all tasks in the harvest_collection DAG.
> Registry output

- record_indexer/index_templates/record_index_config.py
- record_indexer/index_templates/rikolti_template.py
This PR makes the following changes:
Removes `media_source` and `thumbnail_source`. These aren't used in the frontend.
Removes `media.media_filepath` and `thumbnail.thumbnail_filepath` fields. These were duplicative of `media.path` and `thumbnail.path`, respectively.
Adds alias fields for the parent record:
- collection_id --> collection_url
- campus_id --> campus_url
- repository_id --> repository_url
And equivalents for the nested children records:
- children.collection_id --> children.collection_url
- children.campus_id --> children.campus_url
-  children.repository_id -->  children.repository_url
I think this aliasing should work as far as I understand it from reading the OpenSearch documentation.
Running `record_index_config.py` results in the following template:
```
{ …
```
> Remove *_source fields; remove *_filepath fields; add aliases

- record_indexer/settings.py
- record_indexer/update_stage_index.py
I had forgotten to remove this. It was only needed for development.
> Remove STAGE_ALIAS_COMBINED env var

- content_harvester/by_record.py
> Try to get dimensions, but don't raise error if we can't

- metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
> Don't harvest empty_picture.png thumbnails from Nuxeo

- record_indexer/README.md
- record_indexer/index_templates/record_index_config.py
- record_indexer/scripts/copy_index.py
- record_indexer/scripts/copy_rikolti_stg_to_prod.py
- record_indexer/scripts/delete_stage_collection.py
- record_indexer/scripts/reindex_rikolti_stg.py
I updated the `reindex_rikolti_stg` script to poll for task ID. 
In the process, I wound up starting to write my own opensearch python client - probably best to replace it with an actual opensearch python client. 
I've already run the command to update the rikolti index template and I've also already run the `reindex_rikolti_stg` script.
> Reindexing

- dags/shared_tasks/mapping_tasks.py
- metadata_mapper/validator/validation_mode.py
> #1022 - Temporarily skip validator during harvest process.

- dags/shared_tasks/indexing_tasks.py
- dags/unpublish_dag.py
- record_indexer/index_collection.py
Pairs with https://github.com/ucldc/avram/pull/181
Closes #1027
> Add unpublish collection dag

- record_indexer/index_page.py
Bugfix for create_stage_index task
> OS Schema is nested under index name

- metadata_fetcher/fetchers/nuxeo_fetcher.py
I realized that it was unnecessary to be hitting the database twice for every component record.
> Minimize how many times we hit the nuxeo db
