metadata-fetcher/Fetcher.py
metadata-fetcher/NuxeoFetcher.py

Resolve max payload errors from AWS lambda by recursively calling lambda functions to traverse the folderish document tree (this also parallelizes each breadth-traversal of the tree). 
Resolve max recursion level errors when `DEBUG=True` using python's `subprocess` module. (Most of this work is in the main branch already, but since the `NuxeoFetcher` has to specially spawn new processes, this work has affected this PR.)

Nuxeo Fetcher

---

metadata_fetcher/fetch_registry_collections.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/fetchers/oac_fetcher.py
metadata_fetcher/fetchers/oai_fetcher.py
metadata_fetcher/sample_data/nuxeo_harvests.py
metadata_fetcher/sample_data/oac_harvests.py
metadata_fetcher/sample_data/oai_harvests.py
metadata_fetcher/settings.py
metadata_fetcher/tests.py

`metadata_fetcher$ python tests.py` now functional for both json records stored in `metadata_fetcher/sample_data` and Collection API endpoints filtered by harvest type, mapper type, and for individual collections.

Metadata fetcher testing

---

README.md

Project set up instructions worked flawlessly, except these misnamed directories.

Update README with correct directory names

---

metadata_mapper/mappers/mapper.py
metadata_mapper/requirements.txt

I meant to include this in the mapper refactor PR but never pushed it. Not urgent, can follow other things.

Deprecate mapper methods

---

metadata_fetcher/settings.py
metadata_mapper/lambda_function.py
metadata_mapper/map_registry_collections.py
metadata_mapper/mappers/mapper.py
metadata_mapper/mappers/oai/contentdm/arck_mapper.py
metadata_mapper/mappers/oai/contentdm/blackgold_mapper.py
metadata_mapper/mappers/oai/contentdm/chico_mapper.py
metadata_mapper/mappers/oai/contentdm/cvpl_mapper.py
metadata_mapper/mappers/oai/contentdm_mapper.py

This follows https://github.com/ucldc/rikolti/pull/313. It includes everyone's favorite method with a universally disliked name: `split_and_flatten()`. Let's decide what to call it.
It includes:
- oai.contentdm
- oai.contentdm.cvpl
- oai.contentdm.chico
- oai.contentdm.arck
- oai.contentdm.blackgold

1. Implement first round of contentdm mappers

---

metadata_mapper/__init__.py
metadata_mapper/mappers/mapper.py
metadata_mapper/mappers/oai/chapman_mapper.py
metadata_mapper/mappers/oai/contentdm/arck_mapper.py
metadata_mapper/mappers/oai/contentdm/csudh_mapper.py
metadata_mapper/mappers/oai/contentdm_mapper.py
metadata_mapper/mappers/oai/csu_dspace/csuci_mapper.py
metadata_mapper/mappers/oai/oai_mapper.py
metadata_mapper/utilities.py

This is not ready for review. Further changes to the mapper approach are necessary to prevent parent mappers from being called during the build process.

2. Simplify Arck mapper, allow mapping to Callables in the process

---

.github/workflows/ci.yml
.gitignore
Dockerfile
README.md
bin/fetch
bin/install_dev_requirements
bin/lint
bin/map
docker-compose.yml
docker/.ipython/profile_default/startup/bootstrap.py
metadata_mapper/tests.py
metadata_mapper/validate_registry_collections.py
requirements_dev.txt
script/up

@amywieliczka and @barbarahui, I took a little of my own time and Dockerized this project, basically making it so developer environments can be run in a container. I updated the README with instructions, it's quite simple. It primarily facilitates what I have to do a lot when developing locally.
Here are the top line takeaways:
- Using ipython
- Can start console in either the fetcher or mapper module
- Modules inside the cwd are autoloaded when the console starts
- Use `autoreload` to reload all loaded modules
I've tested this, but haven't done any development with it, so I've yet to see how much of an improvement it is, but not having to deal with pyenv, the easy reloading, plus everything else that comes with ipython should make things a bit easier.
Downsides:
- There's a hardcoded …

Set up docker dev env

---

metadata_fetcher/fetch_registry_collections.py
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/flickr_fetcher.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/fetchers/oac_fetcher.py
metadata_fetcher/fetchers/oai_fetcher.py
metadata_fetcher/lambda_function.py

Review bug-fixes PR first
This branch implements some better reporting on fetching tasks:
- `check_page` returns the number of records found on the fetched page, rather than a boolean - updated for the 4 existing fetchers; @lthurston please indicate if this is a problem moving forwards
- `fetch_page` method returns the number of records found on the fetched page, as reported by the `check_page` method
- `lambda_function.fetch_collection` has a more thorough and detailed return value
- `lambda_function.fetch_collection` extends the return value for all pages when run recursively in the local environment
- `fetch_registry_collections.fetch_endpoint` makes use of this return value to provide details about how many records were fetched over how many pages

Fetcher local recursion

---

.gitignore
metadata_mapper/__init__.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/mappers/mapper.py
metadata_mapper/validate_mapping.py
metadata_mapper/validator/__init__.py
metadata_mapper/validator/validation_log.py
metadata_mapper/validator/validation_mode.py
metadata_mapper/validator/validator.py

Enhances the mapping validator with additional functionality:
* Reorganizes validator classes into their own modules within the metadata_mapper package
* `ValidationErrors` is now `ValidationLog`
* Adds `ValidationLogLevel`
* This enum is used to set the logging level
* Options are `ERROR`, `WARNING`, `INFO`, `DEBUG`
* Adds `ValidationMode`
* An enum `STRICT` or `LAX`
* `STRICT` is the current default behavior
* `LAX` performs case-insensitive string comparisons and order-insensitive list comparisons
* Individual validations can define their own `validation_mode` as either `ValidationMode.STRICT` or `ValidationMode.LAX` to override the global default.
* Adds `verbose` option
* Adds successful validation logging at the `INFO` level
* By default, outputs a single line per record, listing …

Validator Improvements Mk. II

---

metadata_mapper/validate_mapping.py
metadata_mapper/validator/validator.py

This PR includes:
- A quick and dirty way to convert couchdb keys into snake case for easy comparison. Amy is going to revisit the names of these fields so, this may only be necessarily in the short term.
- Tweak to validator to use the specified validator class on the vernacular when present, or fall back to Validator.

Validator improvements

---

metadata_mapper/validate_mapping.py

Lines 92-97 return early if the entire page is not found in either Rikolti or Solr, but this means that full pages of new Rikolti records (not found in Solr) and full pages of missing Solr records (not found in Rikolti) are never reported, and that new Rikolti records or missing Solr records are only reported if they sit next to at least one other matched record on the page. 
We definitely want to know if Rikolti harvests 210 records for a collection that has only 110 records in Solr, though! This may be valid, but should be reported and escalated to a person to evaluate what is happening.

Validation skips reporting out full pages of "new" or "missing" records

---

README.md
env.example
metadata_fetcher/README.md
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/lambda_function.py
metadata_fetcher/settings.py
metadata_mapper/lambda_function.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/mappers/mapper.py
metadata_mapper/settings.py
metadata_mapper/utilities.py

`FETCHER_DATA_DEST`, `MAPPER_DATA_DEST`, and `MAPPER_DATA_SRC` should now all be full url paths. If I want to keep the same directory structure as what was previously established, that means setting these env vars to look like this:
```
FETCHER_DATA_DEST=file:///Users/awieliczka/Projects/rikolti/rikolti_bucket
MAPPER_DATA_DEST=file:///Users/awieliczka/Projects/rikolti/rikolti_bucket
MAPPER_DATA_SRC=file:///Users/awieliczka/Projects/rikolti/rikolti_bucket
```
Though it's worth noting that you can now specify any directory as a target directory for storing fetched or mapped metadata files - you are no longer forced to keep files in this particular location. Rikolti will create a `vernacular_metadata/<collection_id>/` folder in the `FETCHER_DATA_DEST` location, and a …

breaking: update local env variables

---

.gitignore
README.md
dags/fetcher_dag.py
dags/operator_sample_dag.py
dags/requirements.txt
dags/startup.sh
dags/taskflow_sample_dag.py
env.example
metadata_fetcher/README.md
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/lambda_function.py
metadata_fetcher/settings.py
metadata_mapper/lambda_function.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/mappers/mapper.py
metadata_mapper/mappers/oac/oac_mapper.py
metadata_mapper/settings.py
metadata_mapper/utilities.py

This is a PR representing the work @barbarahui and I did in writing a first fetcher DAG. Since writing to s3 is not fully supported by the codebase, this work is coordinated with some updates to `ucldc/aws-mwaa-local-runner` described here: https://github.com/ucldc/aws-mwaa-local-runner/pull/3 and is built on top of the DATA_DEST environment variable work here: https://github.com/ucldc/rikolti/pull/495
This PR, in contrast to the DATA_DEST environment variable work, is exclusively DAG-specific work.
- `dags/operate_sample_dag.py` is a DAG written using the classic airflow PythonOperator. 
- `dags/taskflow_sample_dag.py` is a DAG written using the airflow taskflow model. This file also includes a variety of small tasks demonstrating specific, but relevant airflow features. 
- …

Fetcher DAG development

---

.github/workflows/dags_test.yml
README.md
dags/.airflowignore
dags/example_dag.py
dags/test_dag.py
dags/tests.py

Add github workflows for doing basic checking of dags and then deploying them to s3.
Creates a basic dags directory so the tests have something to check

feat: add dags ci github action

---

metadata_mapper/lambda_shepherd.py

Successfully resolves import error locally. 
Interestingly, even including "daguerreotype" in the comments triggers the DAG loader. This is definitely an Airflow bug.

DAG loader mistakenly loads lambda_shepherd due to 'dag' in comments

---

dags/fetcher_dag.py
dags/harvest_dag.py
dags/mapper_dag.py
dags/shared_tasks.py

Factors out all of the reused tasks into `shared_tasks.py`.
It appears that any task that is going to be re-used in multiple dags across multiple files needs to be in a separate file that does not define any dags, otherwise importing that task will also trigger the import of the dag.

fix: factor out shared tasks

---

dags/fetcher_dag.py
dags/harvest_dag.py
dags/mapper_dag.py
dags/shared_tasks.py
dags/taskflow_sample_dag.py
metadata_fetcher/lambda_function.py
metadata_mapper/lambda_shepherd.py

Most notably, this PR creates a `harvest_dag.py` and moves all dag tasks definitions there. Keeping code local to the general case - running the full harvesting pipeline - was helpful in thinking about structuring the inputs and outputs as ideal to this general case. @bibliotechy I can move these back either temporarily (to make reviewing the changes made by this PR within each task a bit easier), or permanently if you think it makes more sense to functionally encapsulate these task definitions. 
This PR also
- standardizes on using `params` method to get dag run parameters (as opposed to `dag_run.conf` or `get_current_context()`)
- standardizes dags as taking a collection id while dag tasks should take a collection metadata resource from the registry API. 
- updates the fetcher task to …

Inputs outputs logs

---

metadata_mapper/mappers/mapper.py

@amywieliczka @barbarahui 
I'm deleting the other PR related to this enrichment, as it's not particularly useful.

Fix cleanup_value enrichment

---

metadata_mapper/validator/validation_log.py

This lets us more easily diff validation reports by guaranteeing an order.

feat: sort validation report before writing to csv

---

metadata_mapper/mappers/oai/cca_vault_mapper.py
metadata_mapper/mappers/oai/oai_mapper.py
metadata_mapper/settings.py
metadata_mapper/validate_mapping.py

@lthurston The TL;DR is that Calisphere IDs are complicated, but should you choose to run the CCA Vault validation locally, you should create a new working branch that merges this branch into any CCA Vault mapper refinements before running the validator in order to effectively compare legacy records with new records. 
------------------------------------------------------------------------------------------
And here's the long explanation of why 🔥Identifiers Are Complicated🔥 😱🤯🥵😮‍💨😵‍💫 
This is likely a meeting discussion at some point @bibliotechy and @barbarahui. I think we're unblocked on evaluating CIC's work for now though, and developing some Airflow tasks feels like the current pressing priority, so I'm leaving some super thorough notes here so we can pick it up later. Major thanks …

CCA Vault Validator ID Workaround

---

README.md
content_harvester/Dockerfile
content_harvester/by_collection.py
content_harvester/by_page.py
content_harvester/docker-compose.yml
content_harvester/settings.py
content_harvester/tests.py
dags/content_dag.py
dags/harvest_dag.py
dags/requirements.txt
dags/samples/airflowisms.py
dags/samples/docker_debug.py
dags/samples/docker_operator.py
dags/samples/dynamic_tasks.py
dags/samples/filesystem.py
dags/samples/operators.py
dags/samples/simple_python_image/Dockerfile
dags/samples/simple_python_image/README.md
dags/samples/simple_python_image/add_one.py
dags/samples/simple_python_image/hello.py
dags/shared_tasks.py
env.example
metadata_fetcher/settings.py
metadata_mapper/lambda_function.py
metadata_mapper/settings.py

This is probably at a good point for review and evaluation. It pipes together a lot of the Dockerfile/docker-compose/mounting/DockerOperator/Airflow Variable work. 
The Content Harvester can be run as a python module (within a system with system level dependencies installed), as a docker container (recommend to use docker-compose), or as a docker operator within the `aws_mwaa_local_runner` ecosystem. This PR:
- Updates the Content Harvester's Dockerfile entrypoint to be congruent with the new import world order (`python -m content_harvester.by_page`)
- Sets up docker-compose for local development by overwriting the entrypoint, mounting `rikolti_data`, `rikolti_content`, and the source code into the container, and sets several environment variables for writing to these mounted volumes. 
- …

Content DAG

---

.gitignore
README.md
content_harvester/by_collection.py
content_harvester/by_page.py
content_harvester/settings.py
content_harvester/tests.py
dags/validate_by_mapper_type.py
harvest.sh
harvest_collection.sh
metadata_fetcher/fetch_registry_collections.py
metadata_fetcher/fetchers/Fetcher.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/map_registry_collections.py
metadata_mapper/mappers/mapper.py
metadata_mapper/mappers/oai/oai_mapper.py
metadata_mapper/settings.py
metadata_mapper/tests.py
metadata_mapper/utilities.py
metadata_mapper/validate_mapping.py
metadata_mapper/validate_registry_collections.py
metadata_mapper/validator/validation_log.py
record_indexer/by_collection.py
record_indexer/settings.py

This PR re-orders the `rikolti_data` folder, adds a `harvest.sh` and `harvest_collection.sh` scripts at the root of the directory (we can remove that `rikolti_bucket_template` branch now - a bucket template is no longer necessary), and adds a DAG to validate by mapper type which performs fetching, mapping, and validating tasks. 
The validate by mapper type dag can take a limit parameter (optional). If none is provided, it validates all collections of that mapper type. If a limit is provided, it validates up to the limit in the order the collections are provided by the registry api. 
This is fully functional but missing some obvious UI pieces, described below, as well as some scalability pieces - notes for myself as much as anyone else: 
Still required to get up and running:
- set up …

[feat]: Validate by mapper type dag

---

metadata_mapper/mappers/mapper.py

will need to re-generate validation reports for flickr, cca_vault, and diff them against existing validation reports to ensure this doesn't create new errors.

Don't overwrite type if registry's dcmi_type is None/X

---

metadata_mapper/mappers/mapper.py

I think this was just a bad migration. Here's the original unset_prop implementation: https://github.com/calisphere-legacy-harvester/dpla-ingestion/blob/cfe3dcb06008c0c6cb9d8207fe28bfaa1a855e4f/lib/akamod/set_prop.py#L63 and here's the blame for the unset_prop function signature: https://github.com/ucldc/rikolti/commit/1a17e423d24eae2bf7eb454c036c19ddc6140dcb 
...I think I must have copied the set_prop function signature to the unset_prop function signature? the fact that "value" is omitted in the analysis of how the enrichment chain calls this enrichment (https://github.com/ucldc/rikolti/blob/main/metadata_mapper/mappers/mapper.py#L829-L831) suggests that "value" just shouldn't even be there.

[bug]: Remove value parameter to unset_prop

---

metadata_mapper/mappers/ucsd_blacklight/ucsd_blacklight_mapper.py

As it turns out, it wasn't affecting the resulting solr doc because the spatial field was being copied into it when it was created. In any case, it should be removed.

Remove coverage field mapping in blacklight

---

docker/.ipython/profile_default/startup/bootstrap_fetcher.py
docker/.ipython/profile_default/startup/bootstrap_mapper.py
docker/.ipython/profile_default/startup/bootstrap_noimport.py
metadata_fetcher/fetchers/Fetcher.py
metadata_mapper/lambda_function.py
metadata_mapper/mappers/oai/chapman_mapper.py
metadata_mapper/mappers/oai/oai_mapper.py

@lthurston I ran the Chapman mapper through the validator and encountered several validation errors. This branch (and PR) is a start at resolving some of the obvious ones:
- Changed identifier mapping: identifier should be a list, not a string
- Added a custom validator to remove errors on http vs. https in identifier and is_shown_at
@christinklez as you continue to evaluate the Chapman mapper, could you reference this PR in the issues you create? @lthurston could you work on this branch to refine the Chapman mapper? 
I'm proposing that this PR becomes a place to centralize ongoing Chapman mapper conversation till such a time that we've approved the Chapman mapper, while individual issues might have a shorter life span and would spec out the details of specific issues - what do you both …

Chapman Mapper Refinements

---

metadata_mapper/mappers/oai/content_dm/contentdm_mapper.py

I couldn't reproduce the error reported in #504, but it did seem to come from an issue calling `resp.json()` when there was no response, so I made this section raise an exception more explicitly.

raise exception if image info request fails

---

metadata_mapper/mappers/flickr/flickr_mapper.py
metadata_mapper/mappers/oai/cca_vault_mapper.py
metadata_mapper/mappers/oai/chapman_mapper.py
metadata_mapper/validator/validator.py

- make `is_shown_by` optional
- add_validatable_fields is a recent addition from Tim to bulk add validation definitions, but there was a small type-based typo preventing it from working correctly
- calisphere links in the validation reports weren't working due to quoting issues

Bug: Validator improvements

---

dags/dev_validate_by_mapper_type_to_gdrive.py
dags/utils_by_mapper_type.py
dags/validate_by_mapper_type.py

This updates the bulk harvesting DAG to run by mapper_type, rikolti_mapper_type, or an arbitrary queryset of collections defined by a Registry API URL. 
It also adds offset capabilities - making it so that we can run the harvester for limited subsets of collections defined at a queryset, and then offset to the next limited subset.

Feat: Bulk harvest collections by registry API url, mapper_type, or rikolti_mapper_type

---

metadata_mapper/mappers/nuxeo/nuxeo_mapper.py
metadata_mapper/mappers/oai/islandora_mapper.py
metadata_mapper/mappers/oai/quartex_mapper.py
metadata_mapper/mappers/oai/samvera_mapper.py
metadata_mapper/validate_mapping.py

- ✨ _feature_: validation report reads 'new record' instead of 'missing record' when record is missing from solr
- ✅ _validation_: `rights` validator ignores phone number discrepancies as long as new phone number is '(310) 825-4988' (legacy data had an auto-incrementing phone number that was clearly wrong)
- ✅ _validation_: `date` validator ignores date discrepancies when old date value is one date, new date value is two dates, the first new date value matches the old date value, and the second date in the new date value is just a YYYY-MM-DD representation of the matching date value. 
- ✅ _validation_: `source` validator ignores discrepancies when old source is ['Los Angeles Times Photographic Collection'] and new source is ['OpenUCLA Collections', 'Los Angeles Times Photographic …

OAI updates

---

env.example
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/calisphere_solr_fetcher.py
metadata_fetcher/fetchers/solr_fetcher.py
metadata_fetcher/settings.py
metadata_mapper/lambda_function.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/map_registry_collections.py
metadata_mapper/mappers/calisphere_solr/calisphere_solr_mapper.py

The mapper is ready for review.
I see what you mean about the solr API returning a final empty page using nextCursorMark. This causes problems when running the `harvest_collection` DAG where the mapper fans out by page. I can't figure out what the heck is going on with Solr.
Since the solr index is static and this is transitional functionality that we'll retire after we cutover to rikolti, I went ahead and added a bit of a hacky workaround to the fetcher's `increment()`  method, which reports "finished" if we've fetched the number of docs that we're expecting. (See this commit: https://github.com/ucldc/rikolti/pull/714/commits/2fe62d02604a53130e98b3e51f21ac3c01d0adc5).

Calisphere etl

---

utils/storage.py
utils/versions.py

This PR adds pagination to the `s3.list_objects_v2()` in `utils.storage.list_s3_pages()` so that we now get results over 1000.
It also fixes a bug that I ran into in `utils.versions.get_version()` where splitting on `f"{collection_id}/` would sometimes return a list of more than 2 elements, e.g. for the following uri:
```8/vernacular_metadata_2024-01-31T00:39:58/data/986```

S3 pagination

---

dags/harvest_dag.py
dags/shared_tasks.py
metadata_fetcher/fetchers/Fetcher.py
metadata_mapper/lambda_function.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/mappers/mapper.py
metadata_mapper/validate_mapping.py

This PR updates the codebase to allow for vernacular pages that do not contain any metadata records. In this case:
- the fetcher issues a warning and writes the API reponse to storage. I figure that storing the page will be helpful for troubleshooting and verifying whether or not the the empty page is harmless
- the mapper issues a warning and mapping/enrichment is skipped
- a mapped_metadata page is not written to storage and `mapped_page_path` in the return dict is set to `None`
The code is also updated in several places to handle a None value for `mapped_page_path`, where before the code was always expecting a string value.
Finally, it fixes a of bug in `mapper.py` where exceptions in enrichments were not getting raised, which was obscuring a problem in `replace_substring()`.

Handle empty md pages

---

metadata_mapper/mappers/calisphere_solr/calisphere_solr_mapper.py
metadata_mapper/validator/validator.py
record_indexer/index_templates/record_index_config.json

I don't think any of these fields need custom validators since we're comparing the content to what's currently in Solr, but if you think it's a good idea then let me know. Some fields that are funky (they have `::` as a separator): campus_data, collection_data, repository_data.

Add default validations for addt'l fields not specified in UCLDC_map()

---

content_harvester/by_record.py
content_harvester/requirements.txt

Doesn't add `reference_image_dimensions` to the Open Search index, but does add `dimensions` into the `thumbnail` datastructure, which I believe goes directly into Open Search?

Add thumbnail dimensions; add pillow req to content_harvester img

---

dags/shared_tasks/shared.py

- Resolves issue where dag-level callbacks were failing (resulting in never sending a `dag_complete` message to the registry.
- Resolves issue where failure callbacks were failing (resulting in never sending an `error` message to the registry.
- Resolves issue where send_event_to_sns fails noisily if permissions to create an sns client are unavailable.
- Resolves issue where try_number was not consistently getting reported, turns out `task_instance.try_number` is *not* the current try number, but is actually the try_number the next time the task will run. It's complicated. `task_instance.pre_attempted_tries` is stable. 
- Adds 'version' and 'host' to the the event message, to support different airflow hosts, and version to allow the Registry's `rikolti_status` command to switch on …

Rikolti event stream updates

---

metadata_mapper/mappers/calisphere_solr/calisphere_solr_mapper.py

For all other mapper types, these 3 fields are mapped in `solr_updater`. However, we don't run `solr_updater` for ETL collections, so these mappings needed to be added to the calisphere_solr mapper itself.

Add `url_item`, `fetcher_type` and `mapper_type` to calisphere_solr mapper

---

content_harvester/by_record.py

@amywieliczka I wanted to run this by you before merging since I know you've done some work on how best to approach capturing exceptions and bubbling up the info to the airflow logs. I think it's pretty straightforward though? Printing the calisphere-id along with the error from PIL will let us hone in on which specific image is problematic.

Capture PIL errors and print calisphere-id

---

metadata_fetcher/fetchers/nuxeo_fetcher.py

We don't need to recursively call `folder_traversal()`. The initial nuxeo query fetches all folders at a particular path already. Calling it again means that deeply nested folders are fetched again, resulting in duplicate pages of records.

Fix recursion bug in nuxeo fetcher

---

dags/shared_tasks/content_harvest_operators.py

We are getting `(ThrottlingException): Rate exceeded` errors from the ContentHarvestEcsOperator when harvesting very large collections. Attempting to mitigate this per this advice:
https://airflow.apache.org/docs/apache-airflow-providers-amazon/stable/connections/aws.html#avoid-throttling-exceptions

Set AWS_RETRY_MODE and AWS_MAX_ATTEMPTS to mitigate throttling errors

---

dags/shared_tasks/content_harvest_operators.py

Increase the number of max_waiter_attempts to 1440. We will poll ECS every 10 seconds (waiter_delay) up to 1440 times. The end effect is that Airflow will poll ECS for a max of 4 hours to see if the task is finished before giving up.

Increase waiter max attempts to 720 for content harvester operator

---

content_harvester/README.md
metadata_mapper/mappers/constants.py

This is related to these 2 PRs:
https://github.com/ucldc/rikolti/pull/890
https://github.com/ucldc/rikolti/pull/893
I'm not sure that adding `video/quicktime` to `type_map` will actually have any effect in practice, but it seemed prudent to update both this and the README.

Update README and constants for new content mimetypes (quicktime & png)

---

record_indexer/add_page_to_index.py

We are putting this in place temporarily just to get us through to MVP. Post-MVP, we will discuss whether or not to support an item being part of multiple collections.

Print warning and allow doc creation to fail for id collisions

---

content_harvester/by_registry_endpoint.py
metadata_fetcher/fetch_registry_collections.py
metadata_mapper/map_registry_collections.py
record_indexer/scripts/update_sort_collection_data.py
utils/registry_client.py

Update sort_collection_data for ETL'ed collections from 
`<sortable name>::<display name>::https:://registry.cdlib.org/api/v1/collection/<collection id>`
to 
`<sortable name>::<display name>::<collection id>`
and revert any instances of `::` in the display name back to `:`.

948 update sort collection data

---

metadata_fetcher/fetchers/nuxeo_fetcher.py

This fixes an ordering bug we encountered when using the @search endpoint.

Update nuxeo API endpoint for fetching child objects

---

record_indexer/index_templates/record_index_config.py

This is really just one commit on top of #1012 Index Version Path, since both PRs require reindexing, though, I've made this PR against the `index-version-path` update. 
We will need to reindex both the stage and prod indexes once this update is in place. Closes #1018

Add lowercase_trim normalizer to type.raw field

---

content_harvester/by_record.py

I am still scratching my head over why this is the case, but it seems that if you use a function call as the default value for `dict.get()`, then the function call always runs, even if the key exists in the dictionary.
[Update]: OK so this makes sense. This is because, for any function call, python evaluates the arguments before the function call is executed. So for the following statement:
```
thumbnail_src = record.get('thumbnail_source', get_thumb_src(record))
```
Python runs `get_thumb_src(record)` first, before running `record.get()`.
Running `get_thumb_src(record)` updates the `record` dict "in place", so that the value of `record['thumbnail_source']` becomes:
```
{'url': {'url': 'https://nuxeo.cdlib.org/nuxeo/nxfile/default/19c41b7c-36ef-470d-bced-761046a3eb72/file:content/mss86-4_0 …
```

Don't use default value when doing dict lookup for 'thumbnail_source'

---

content_harvester/by_record.py

The disk is filling up during content harvesting. I think the file removal statements in this bit of code got dropped during the recent caching implementation: https://github.com/ucldc/rikolti/blob/9f7be231bd24dbb8b5e34e8b1c7554e59e4e5ada/content_harvester/by_record.py#L149-L156
The code in this PR removes source files and derivative files from local disk once they're no longer needed. I tried to find a neater way to remove the files all at once, i.e. at the end of `harvest_record_content`, but it proved tricky.
I also made a change to `derivatives.subprocess_exception_handler` so that it raises an error instead of returning None if there is an error. As was, the DAG was succeeding even when, for example, the `pdf_to_thumb` subprocess was failing. It seemed like the return value of `None` …

Content harvest rm tmp files

---

README.md
content_harvester/README.md
content_harvester/by_collection.py
content_harvester/by_page.py
content_harvester/by_record.py
content_harvester/docker-compose.yml
dags/dev_dags/mapper_dag.py
dags/harvest_dag.py
dags/shared_tasks/content_harvest_operators.py
dags/shared_tasks/indexing_tasks.py
dags/shared_tasks/mapping_tasks.py
env.example
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/fetchers/ucd_json_fetcher.py
metadata_mapper/lambda_function.py
metadata_mapper/lambda_shepherd.py
metadata_mapper/map_registry_collections.py
metadata_mapper/validate_mapping.py
record_indexer/index_page.py
utils/s3copy.py
utils/storage.py
utils/versions.py

This PR:
- Deprecates `VERNACULAR_DATA`, `MAPPED_DATA`, `WITH_CONTENT_URLS_DATA`, and `MERGED_DATA` environment variables in favor of `RIKOLTI_DATA`. 
- Updates `CONTENT_ROOT` to `RIKOLTI_CONTENT`
- Adds a `python -m utils.s3copy` utility that takes an s3 URI & a local filesystem path to pull down to the local filesystem some arbitrary s3 folder, maintaining relative paths.

One RIKOLTI_DATA to rule them all

---

metadata_mapper/mappers/date_enrichments.py

Date values like this: ["1494; 1495"] look like this after enrichment: ["1494", " 1495"]
Note the space before "1495". Not sure how critical it is to remove this, but the validation report was flagging it as a problem, and maybe it affects the decade faceting?

Strip date string after splitting on ;

---

content_harvester/by_record.py

@amywieliczka As we discussed, the updates in this PR set the media component to have`mimetype=None` and `path=None` by default. We then check to see if the component `path` is set, and don't set `record['media']` on the record unless it is. This essentially restores the old behavior of the content harvester.
I think that if we instead added the incomplete `media` field to the index, e.g.:
```
"media": {
'mimetype': None,
'path': None,
'format': "image"
}
```
then this would get through to the hosted-simple-image template in the frontend based on the fact that it's a hosted image. Then this line would cause an error because `item.contentFile.titleSources` was empty:
https://github.com/ucldc/public_interface/blob/main/calisphere/templates/calisphere/objectViewer/hosted-simple-image.html#L33 …

Allow for failure of media component derivative creation

---

content_harvester/by_record.py

Updates the content_harvester's component cache storing and retrieval:
- cache all media and thumbnail components, even if etag and last-modified data isn't in the response header. If etag and last-modified aren't in the response header, uses `<collection_id>/<content_src_url>/<media OR thumbnail>` as the cache key
- do not cache media and thumbnail components if the component's s3 path is `None` - if the component's s3 path is `None`, an error probably occurred and we'll want to retry, or fix the error and retry. 
- use cached components if we have an exact match on a 5-part key `<collection_id>/<content_src_url>/<media OR thumbnail>/<etag>/<last-modified>` OR if we have an exact match on a 3-part key `<collection_id>/<content_src_url>/<media OR thumbnail>` and the cached component's …

Aggressive Caching

---

dags/shared_tasks/mapping_tasks.py
env.example
metadata_mapper/settings.py
metadata_mapper/validate_mapping.py

This PR removes use of `UCLDC_COUCH_URL` and `UCLDC_COUCH_TIMEOUT` env vars from the codebase, as CouchDB is no longer running.
When running the `harvest_collection` dag, the validation report generation was getting skipped. We decided to reinstate it.
When running the validator, the reports will be created without validating `isShownAt` and `isShownBy`, since those validations rely on CouchDB data. 
I did not actually do the work of stripping out all of the logic relating to couchdb. I figure it makes sense to do that when we overhaul the validator to compare against OpenSearch data.
There is also a 2nd commit in this PR that I think fixes a logic error: https://github.com/ucldc/rikolti/pull/1149/commits/64277b55ef80e2fc83a5711e9adba214d5206e20

Remove couchdb env vars

---

content_harvester/by_record.py
metadata_fetcher/fetchers/Fetcher.py
metadata_fetcher/fetchers/flickr_fetcher.py
metadata_fetcher/fetchers/nuxeo_fetcher.py
metadata_fetcher/fetchers/oac_fetcher.py
metadata_fetcher/fetchers/ucd_json_fetcher.py
metadata_mapper/mappers/oai/content_dm/contentdm_mapper.py
metadata_mapper/mappers/oai/islandora_mapper.py
metadata_mapper/mappers/oai/omeka_mapper.py
utils/request_retry.py

- implement retries in base Fetcher class
- move `make_http_request()` functionality into `ucd_json_fetcher` -- this is the only place this was being used

Fetcher retries

---

metadata_fetcher/fetchers/nuxeo_fetcher.py

The main difference here, other than hitting the dbquery lambda endpoint, is that recursing down the hierarchy of documents is implemented here in the fetcher code rather than in the lambda.

Update nuxeo fetcher to use db query lambda
